version: '2'
services:
  odoo:
    image: lups/odoo:9.0
    environment:
      DATABASE_HOST: "postgres"
      DATABASE_USER: "odoo"
      DATABASE_PASSWORD: "odoo"
      DATABASE_NAME: "odoo"
    links:
     - postgres
    depends_on:
     - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "odoo"
      POSTGRES_PASSWORD: "odoo"
      POSTGRES_DB: "odoo"
